name: Kamal Deploy
description: GitHub Action to build and deploy Docker image with Kamal
color: 'blue'
inputs:
  environment:
    description: 'Application environment, will be passed to Kamal as --destination flag'
    required: false
  registry-username:
    description: 'Registry username'
    required: true
  registry-password:
    description: 'Registry password'
    required: true
  kamal-path:
    description: 'Path to the Kamal binary file'
    required: false
    default: './bin/kamal'
runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'anchor'
  color: 'blue'